version : "3.9"

services : 
  app :
    build : 
      context : .
    ports: 
      - "8000:8000"
    volumes:
      - ./carnot:/carnot
    command : >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on :    
      - cache
    
  
  cache:
    image : redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  


volumes :
  cache:
    driver: local

